// Generates src/assets/codemirror-editor.umd.js, copies src/assets/codemirror/, and
// copies src/assets/webview-interface.umd.js from node_modules.
// Run via `npm run copy-assets`. Called automatically by `npm run prepare`.
'use strict';

const { resolve } = require('path');
const { readFileSync, writeFileSync, rmSync, cpSync, copyFileSync } = require('fs');

const ROOT = resolve(__dirname, '..');
const PKG_DIST = resolve(ROOT, 'node_modules/@actualwave/js-codemirror-package/dist');
const WEBVIEW_INTERFACE_PKG = resolve(ROOT, 'node_modules/@actualwave/webview-interface');
const ASSETS_DIR = resolve(ROOT, 'src/assets');

// Strip ESM import/export syntax so the code can run as a plain <script> in the WebView.
// Only top-level import/export lines are removed — the logic is intentionally narrow.
function stripEsmSyntax(code) {
  return code
    // Remove: import { ... } from '...';
    .replace(/^import\s+.*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, '')
    // Remove: export { ... };
    .replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '')
    // Remove 'export' keyword before declarations (const, function, async function, class)
    .replace(/^export\s+((?:async\s+)?(?:function|const|let|var|class)\b)/gm, '$1');
}

function buildIife() {
  const loaderSrc = readFileSync(resolve(PKG_DIST, 'requireAsyncModule.js'), 'utf8');
  const indexSrc = readFileSync(resolve(PKG_DIST, 'index.js'), 'utf8');

  const body = [
    stripEsmSyntax(loaderSrc),
    stripEsmSyntax(indexSrc),
    'global.CodeMirrorEditor = { configure, createEditor, requireAsyncModule, registerExtension };',
  ].join('\n');

  const iife = [
    '// Generated by scripts/copy-assets.js — do not edit directly.',
    '// Source: node_modules/@actualwave/js-codemirror-package/dist/',
    '// Plain IIFE bundle (no import/export) for loading via <script> in Android WebView.',
    '// Exposes: window.CodeMirrorEditor = { configure, createEditor, requireAsyncModule, registerExtension }',
    "(function (global) {",
    "'use strict';",
    body,
    "})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);",
  ].join('\n');

  writeFileSync(resolve(ASSETS_DIR, 'codemirror-editor.umd.js'), iife, 'utf8');
  console.log('  wrote src/assets/codemirror-editor.umd.js');
}

function copyCodemirrorModules() {
  const src = resolve(PKG_DIST, 'codemirror');
  const dest = resolve(ASSETS_DIR, 'codemirror');
  rmSync(dest, { recursive: true, force: true });
  cpSync(src, dest, { recursive: true });
  console.log('  copied src/assets/codemirror/');
}

function copyWebviewInterface() {
  copyFileSync(
    resolve(WEBVIEW_INTERFACE_PKG, 'webview-interface.umd.js'),
    resolve(ASSETS_DIR, 'webview-interface.umd.js'),
  );
  console.log('  copied src/assets/webview-interface.umd.js');
}

console.log('Copying assets from node_modules...');
buildIife();
copyCodemirrorModules();
copyWebviewInterface();
console.log('Done.');
